###########################

# AUTOSTART PROGRAMS (db) #

###########################





exec-once = hyprpm reload -n

exec-once = dunst

exec-once = blueman-applet

exec-once = nm-applet

exec-once = swww-daemon

exec-once = ags run --gtk 3 ~/.config/ags/app.ts

exec-once = sleep 1 && swww img /home/db/Pictures/wallpapers/db.jpg



monitor = eDP-1,1920x1080@60,0x0,1.33



$terminal = foot



bind = SUPER, Q, exec, $terminal

bind = SUPER, RETURN, exec, $terminal

bind = SUPER, M, exit

bind = SUPER, R, exec, hyprctl reload

bind = SUPER SHIFT, Q, exec, kill -9 $(hyprctl activewindow -j | jq '.pid')

bind = SUPER, SPACE, exec, wofi --show drun --normal-window

bind = SUPER, S, exec, foot -e nano ~/dbshortcuts.txt

bind = SUPER, left, movefocus, l

bind = SUPER, right, movefocus, r

bind = SUPER, up, movefocus, u

bind = SUPER, down, movefocus, d

bind = , Print, exec, grim - | wl-copy

bind = SHIFT, Print, exec, grim -g "$(slurp)" - | wl-copy

bind = ALT, TAB, hyprexpo:expo, toggle

bind = SUPER, F, fullscreen

bind = SUPER SHIFT, F, exec, /home/db/bin/dbfloatall

bind = SUPER, B, exec, /home/db/bin/dbtogglebar

bindm = SUPER, mouse:272, movewindow

bindm = SUPER, mouse:273, resizewindow

# Theme switcher keybinds
bind = SUPER, F1,  exec, /home/db/bin/dbtheme db
bind = SUPER, F2,  exec, /home/db/bin/dbtheme forest
bind = SUPER, F3,  exec, /home/db/bin/dbtheme goretex
bind = SUPER, F4,  exec, /home/db/bin/dbtheme lain
bind = SUPER, F5,  exec, /home/db/bin/dbtheme omarchy
bind = SUPER, F6,  exec, /home/db/bin/dbtheme arizona
bind = SUPER, F7,  exec, /home/db/bin/dbtheme b
bind = SUPER, F8,  exec, /home/db/bin/dbtheme bazzerk
bind = SUPER, F9,  exec, /home/db/bin/dbtheme cathedral
bind = SUPER, F10, exec, /home/db/bin/dbtheme cumulonimbus
bind = SUPER, F11, exec, /home/db/bin/dbtheme oilpaint
bind = SUPER, F12, exec, /home/db/bin/dbtheme paint
bind = SUPER SHIFT, F1, exec, /home/db/bin/dbtheme windows
bind = SUPER SHIFT, F2, exec, /home/db/bin/dbtheme zenin

general {

    border_size = 3

    gaps_in = 6

    gaps_out = 12

    col.active_border = rgba(0078d7cc)

    col.inactive_border = rgba(102040aa)

}



decoration {

    rounding = 12



    active_opacity = 0.9

    inactive_opacity = 0.70

    fullscreen_opacity = 1.0



    shadow {

        enabled = true

        range = 35

        render_power = 3

        color = rgba(0078d7cc)

    }



    blur {

        enabled = true

        size = 8

        passes = 3

        new_optimizations = true

    }

}



animations {

    enabled = yes



    bezier = db_smooth, 0.05, 0.9, 0.1, 1.0

    bezier = linear, 0.0, 0.0, 1.0, 1.0



    animation = global,        1, 7, db_smooth

    animation = windows,       1, 6, db_smooth, popin 80%

    animation = windowsIn,     1, 6, db_smooth, popin 80%

    animation = windowsOut,    1, 5, db_smooth, popin 80%

    animation = fade,          1, 5, db_smooth

    animation = fadeIn,        1, 5, db_smooth

    animation = fadeOut,       1, 5, db_smooth

    animation = border,        1, 4, db_smooth

    animation = workspaces,    1, 6, db_smooth, slide

    animation = workspacesIn,  1, 6, db_smooth, slide

    animation = workspacesOut, 1, 6, db_smooth, slide

}

misc {
    background_color = 0x000000
}



plugin {
    hyprexpo {
        columns = 3
        gap_size = 8
        bg_col = rgb(000000)
        workspace_method = center current

        enable_gesture = false
    }

    dynamic-cursors {
        mode = tilt

        threshold = 2

        shake {
            enabled = true
            threshold = 4.0
            factor = 1.5
        }
    }
}
